/**
 * Development-only ambient declarations.
 *
 * This package is consumed inside an Astro project, where `astro:content`, the
 * `virtual:starlight/*` modules and Starlight's `App.Locals` augmentation are
 * all generated by the build. None of that exists when typechecking the package
 * on its own, so the minimal surface this code touches is declared here.
 *
 * NOT PUBLISHED — see the `files` field in package.json. Consumers get the real
 * declarations from their own project.
 */

declare module 'astro:content' {
	export type CollectionEntry<C extends string = string> = {
		collection: C;
		id: string;
		body?: string | undefined;
		filePath?: string | undefined;
		data: Record<string, any>;
	};
	export type DataCollectionKey = string;
	export type RenderResult = { Content: any; headings: any[]; remarkPluginFrontmatter: any };
	export function getCollection(collection: string): Promise<CollectionEntry[]>;
}

declare namespace App {
	interface Locals {
		starlightRoute: import('@astrojs/starlight/route-data').StarlightRouteData;
		t: (key: string) => string;
	}
}

declare namespace StarlightApp {
	interface I18n {}
}

declare module 'virtual:starlight/user-config' {
	const config: any;
	export default config;
}
declare module 'virtual:starlight/project-context' {
	const context: any;
	export default context;
}
declare module 'virtual:starlight/plugin-translations' {
	const translations: any;
	export default translations;
}
declare module '*.jsonc?raw' {
	const content: string;
	export default content;
}
